# Step 1: Do an item query


In [1]:
import psycopg2
import config as config

In [2]:
conn = config.connect()
cursor = conn.cursor()

In [3]:
import teamQuery as tq

In [4]:
len(tq.teamQueryCounts("Redskins"))

411

In [5]:
red = tq.teamQueryTexts('Redskins')

In [6]:
corp = [text[3] for text in red]

In [7]:
len(corp)

411

In [8]:
type(corp[1])

str

In [9]:
len(corp[1])

5167

# Step 2: Gensim 3.2.0

In [1]:
import gensim

c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\gensim\utils.py:860: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [2]:
id2word = gensim.corpora.Dictionary.load_from_text('wiki_en_wordids.txt') ## Lets obtain this dictionary from Wikipedia

FileNotFoundError: [Errno 2] No such file or directory: 'wiki_en_wordids.txt'

# Step 3: Graphlab with special API instructions

In [3]:
import graphlab as gl

ModuleNotFoundError: No module named 'graphlab'

# Step 4: lda 1.0.5

In [10]:
import lda

In [11]:
X = lda.datasets.load_reuters() ## Don't know what this is

In [12]:
len(X)

395

In [14]:
print(X)

[[1 0 1 ... 0 0 0]
 [7 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]]


In [16]:
model = lda.LDA(n_topics=20, n_iter=1500, random_state=1)

In [18]:
z = model.fit(X)

INFO:lda:n_documents: 395
INFO:lda:vocab_size: 4258
INFO:lda:n_words: 84010
INFO:lda:n_topics: 20
INFO:lda:n_iter: 1500
INFO:lda:<0> log likelihood: -1051748
INFO:lda:<10> log likelihood: -719800
INFO:lda:<20> log likelihood: -699115
INFO:lda:<30> log likelihood: -689370
INFO:lda:<40> log likelihood: -684918
INFO:lda:<50> log likelihood: -681322
INFO:lda:<60> log likelihood: -678979
INFO:lda:<70> log likelihood: -676598
INFO:lda:<80> log likelihood: -675383
INFO:lda:<90> log likelihood: -673316
INFO:lda:<100> log likelihood: -672761
INFO:lda:<110> log likelihood: -671320
INFO:lda:<120> log likelihood: -669744
INFO:lda:<130> log likelihood: -669292
INFO:lda:<140> log likelihood: -667940
INFO:lda:<150> log likelihood: -668038
INFO:lda:<160> log likelihood: -667429
INFO:lda:<170> log likelihood: -666475
INFO:lda:<180> log likelihood: -665562
INFO:lda:<190> log likelihood: -664920
INFO:lda:<200> log likelihood: -664979
INFO:lda:<210> log likelihood: -664722
INFO:lda:<220> log likelihood: -

In [21]:
type(z)   ## Success to this point

lda.lda.LDA

In [22]:
model

# Step 5: Scikit-Learn 0.19.1

In [2]:
from sklearn.decomposition import NMF, LatentDirichletAllocation

In [24]:
X

array([[1, 0, 1, ..., 0, 0, 0],
       [7, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [25]:
lda = LatentDirichletAllocation(n_topics=20, max_iter=5, random_state=0)

In [26]:
lda.fit(X)

c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)
c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\sklearn\decomposition\online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=5,
             mean_change_tol=0.001, n_components=10, n_jobs=1, n_topics=20,
             perp_tol=0.1, random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [27]:
lda

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=5,
             mean_change_tol=0.001, n_components=10, n_jobs=1, n_topics=20,
             perp_tol=0.1, random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [28]:
## Pipline Example
from sklearn.datasets import fetch_20newsgroups

#Initialize Variables
n_samples = 2000
n_features = 1000
n_topics = 10

dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))

INFO:sklearn.datasets.twenty_newsgroups:Downloading 20news dataset. This may take a few minutes.
INFO:sklearn.datasets.twenty_newsgroups:Downloading dataset from https://ndownloader.figshare.com/files/5975967 (14 MB)


In [30]:
len(dataset['data'])

11314

In [31]:
data_samples = dataset.data[:n_samples]

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

# Setup a tf vectorizer
tf_vectorizer = CountVectorizer(max_df=0.95,
                                min_df=2,
                                max_features=n_features,
                                stop_words='english')

tf = tf_vectorizer.fit_transform(data_samples)

In [37]:
lda = LatentDirichletAllocation(n_topics=20,
                               max_iter=5,
                               learning_method='online',
                               learning_offset=50.,
                               random_state=0)

In [38]:
tf

<2000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 51752 stored elements in Compressed Sparse Row format>

In [39]:
lda.fit(tf)  ## Success to this point

c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=5, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=20, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

# Step 6: NMF and LDA from scikit-learn docs

In [1]:
n_samples = 2000
n_features = 1000
n_topics = 10
n_top_words = 10

In [2]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import NMF, LatentDirichletAllocation
from time import time

In [18]:
# Nice Tokenizers
import nltk
from nltk.stem import SnowballStemmer, WordNetLemmatizer

base_tokenizer = CountVectorizer().build_tokenizer()
stemmer = SnowballStemmer('english')
lemmatizer = WordNetLemmatizer()

tokenize = None
tokenize = lambda text: [stemmer.stem(item) for item in base_tokenizer(text)]
#tokenize = lambda text: [lemmatizer.lemmatize(item) for item in base_tokenizer(text)]

In [14]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Anthony\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [17]:
tokenize('what the hell is this yell yeller yells')

['what', 'the', 'hell', 'is', 'this', 'yell', 'yeller', 'yell']

In [20]:
# Load the 20 newsgroups dataset and vectorize it.  
# Use a few heuristics to filter out useless terms early on, the posts are stripped of headers,
# footers and quotes replies, and common english words, words occuring in only one document
# or in at least 95% of the documents re removed.

print("Loading dataset...")
t0 = time()
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
data_samples = dataset.data[:n_samples]
print("done in %0.fs." % (time() - t0))

Loading dataset...
done in 3s.


In [4]:
len(dataset.data)

11314

In [29]:
# TF-IDF Vectorization
print("Extracting tf-idf features for NMF...")
tfidf_vectorizer = TfidfVectorizer(max_df=.95,
                                   min_df=2,
                                   max_features=n_features,
                                   ngram_range=(1,3),
                                   tokenizer=tokenize,
                                   stop_words='english')

t0 = time()
tfidf = tfidf_vectorizer.fit_transform(data_samples)
print("done in %0.3fs." % (time() - t0))


Extracting tf-idf features for NMF...
done in 13.296s.


In [30]:
featuresIdf = tfidf_vectorizer.get_feature_names()

In [31]:
len(featuresIdf)

1000

In [8]:
# TF Vectorization - raw term counts
print("Extracting tf features for LDA...")
tf_vectorizer = CountVectorizer(max_df=.95,
                                min_df=2,
                                ngram_range=(1,3),
                                max_features=n_features,
                                stop_words='english')

t0 = time()
tf = tf_vectorizer.fit_transform(data_samples)
print('done in %0.3fs.' % (time() - t0))

Extracting tf features for LDA...
done in 3.054s.


In [9]:
features = tf_vectorizer.get_feature_names()

In [10]:
type(features)

list

In [11]:
tfidf.shape

(2000, 1000)

In [12]:
tf.shape

(2000, 1000)

In [32]:
# The print top words function
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        message = "Topic #%d: " % topic_idx
        message += " ".join([feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)
    print()
        

In [33]:
# NMF Model

In [34]:
print("Fitting the NMF model with tf-idf freatures,  "
      'n_samples=%d and n_features=%d...'
      % (n_samples, n_features))

t0 = time()

nmf = NMF(n_components=n_topics,
          random_state=1,
          alpha=.1,
          l1_ratio=.5)

nmfResult = nmf.fit(tfidf)
print("done in %0.3fs." % (time() - t0))

tfidf_feature_names = tfidf_vectorizer.get_feature_names()

Fitting the NMF model with tf-idf freatures,  n_samples=2000 and n_features=1000...
done in 0.266s.


In [35]:
tfidf.shape

(2000, 1000)

In [36]:
nmf.components_.shape

(10, 1000)

In [37]:
print("Topics in NMF model:")
print_top_words(nmf, tfidf_feature_names, n_top_words)

Topics in NMF model:
Topic #0: like just don think peopl use time make know ani
Topic #1: window use program dos applic driver run os manag work
Topic #2: god christian jesus bibl faith believ sin religion christ exist
Topic #3: thank anyon pleas mail ani doe know advanc doe anyon thank advanc
Topic #4: game team play win player season year score blue defens
Topic #5: drive disk floppi hard card problem mac rom control softwar
Topic #6: edu bank soon internet univers mit edu articl com send ftp
Topic #7: key chip encrypt clipper govern use secur phone public law enforc
Topic #8: file problem format ftp pub site sound avail convert help
Topic #9: car mile tire buy price model brake insur new dealer



In [38]:
# NMF Model with generalized Kullback-Leibler divergence

In [39]:
print("Fitting the NMF model (generalized Kullback-Leibler divergence) with tf-idf freatures,  "
      'n_samples=%d and n_features=%d...'
      % (n_samples, n_features))

t0 = time()

nmf = NMF(n_components=n_topics,
          random_state=1,
          beta_loss='kullback-leibler',
          solver='mu',
          max_iter=1000,
          alpha=.1,
          l1_ratio=.5)

nmfResult = nmf.fit(tfidf)
print("done in %0.3fs." % (time() - t0))

tfidf_feature_names = tfidf_vectorizer.get_feature_names()

Fitting the NMF model (generalized Kullback-Leibler divergence) with tf-idf freatures,  n_samples=2000 and n_features=1000...
done in 4.920s.


In [40]:
print("Topics in NMF model:")
print_top_words(nmf, tfidf_feature_names, n_top_words)

Topics in NMF model:
Topic #0: like use onli make time peopl just way right veri
Topic #1: use window thank ani help file pleas run look need
Topic #2: god say doe question peopl know true refer ani whi
Topic #3: thank anyon pleas post know like mail want someon just
Topic #4: time year team win game ve play onli player didn
Topic #5: drive onli work power need hard new time sale thing
Topic #6: edu univers includ com space write articl group year internet
Topic #7: use number data key chip doe world bit receiv phone
Topic #8: think don like know whi say tri just wrong need
Topic #9: good just veri want tri work use realli new look



In [ ]:
# LDA Model

In [68]:
print("Fitting the LDA model  with tf freatures,  "
      'n_samples=%d and n_features=%d...'
      % (n_samples, n_features))

t0 = time()

lda = LatentDirichletAllocation(n_components=n_topics,
                                max_iter=5,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0,
                                )

lda.fit(tf)
print("done in %0.3fs." % (time() - t0))

tf_feature_names = tf_vectorizer.get_feature_names()

Fitting the LDA model  with tf freatures,  n_samples=2000 and n_features=1000...
done in 7.212s.


In [69]:
print("Topics in LDA model:")
print_top_words(lda, tf_feature_names, n_top_words)

Topics in LDA model:
Topic #0: space 10 earth 12 moon surface probe 93 00 lunar
Topic #1: game scsi play team flyers season games cubs color points
Topic #2: people just don think like know god time say make
Topic #3: thanks know like does bike don help interested advance looking
Topic #4: section military division win weapon firearm dangerous license shall application
Topic #5: edu windows com file mail graphics version software send ftp
Topic #6: just car like new good don year think better cars
Topic #7: 55 11 10 18 15 17 25 26 22 23
Topic #8: health hiv new national president aids information disease pittsburgh united
Topic #9: drive disk card hard drives speed power controller hard disk rom

