# Step 1: Do an item query


In [1]:
import psycopg2
import config as config

In [2]:
conn = config.connect()
cursor = conn.cursor()

In [3]:
import teamQuery as tq

In [4]:
len(tq.teamQueryCounts("Redskins"))

411

In [5]:
red = tq.teamQueryTexts('Redskins')

In [6]:
corp = [text[3] for text in red]

In [7]:
len(corp)

411

In [8]:
type(corp[1])

str

In [9]:
len(corp[1])

5167

# Step 2: Gensim 3.2.0

In [1]:
import gensim

c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\gensim\utils.py:860: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [2]:
id2word = gensim.corpora.Dictionary.load_from_text('wiki_en_wordids.txt') ## Lets obtain this dictionary from Wikipedia

FileNotFoundError: [Errno 2] No such file or directory: 'wiki_en_wordids.txt'

# Step 3: Graphlab with special API instructions

In [3]:
import graphlab as gl

ModuleNotFoundError: No module named 'graphlab'

# Step 4: lda 1.0.5

In [10]:
import lda

In [11]:
X = lda.datasets.load_reuters() ## Don't know what this is

In [12]:
len(X)

395

In [14]:
print(X)

[[1 0 1 ... 0 0 0]
 [7 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]]


In [16]:
model = lda.LDA(n_topics=20, n_iter=1500, random_state=1)

In [18]:
z = model.fit(X)

INFO:lda:n_documents: 395
INFO:lda:vocab_size: 4258
INFO:lda:n_words: 84010
INFO:lda:n_topics: 20
INFO:lda:n_iter: 1500
INFO:lda:<0> log likelihood: -1051748
INFO:lda:<10> log likelihood: -719800
INFO:lda:<20> log likelihood: -699115
INFO:lda:<30> log likelihood: -689370
INFO:lda:<40> log likelihood: -684918
INFO:lda:<50> log likelihood: -681322
INFO:lda:<60> log likelihood: -678979
INFO:lda:<70> log likelihood: -676598
INFO:lda:<80> log likelihood: -675383
INFO:lda:<90> log likelihood: -673316
INFO:lda:<100> log likelihood: -672761
INFO:lda:<110> log likelihood: -671320
INFO:lda:<120> log likelihood: -669744
INFO:lda:<130> log likelihood: -669292
INFO:lda:<140> log likelihood: -667940
INFO:lda:<150> log likelihood: -668038
INFO:lda:<160> log likelihood: -667429
INFO:lda:<170> log likelihood: -666475
INFO:lda:<180> log likelihood: -665562
INFO:lda:<190> log likelihood: -664920
INFO:lda:<200> log likelihood: -664979
INFO:lda:<210> log likelihood: -664722
INFO:lda:<220> log likelihood: -

In [21]:
type(z)   ## Success to this point

lda.lda.LDA

In [22]:
model

# Step 5: Scikit-Learn 0.19.1

In [2]:
from sklearn.decomposition import NMF, LatentDirichletAllocation

In [24]:
X

array([[1, 0, 1, ..., 0, 0, 0],
       [7, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [25]:
lda = LatentDirichletAllocation(n_topics=20, max_iter=5, random_state=0)

In [26]:
lda.fit(X)

c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)
c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\sklearn\decomposition\online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=5,
             mean_change_tol=0.001, n_components=10, n_jobs=1, n_topics=20,
             perp_tol=0.1, random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [27]:
lda

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=5,
             mean_change_tol=0.001, n_components=10, n_jobs=1, n_topics=20,
             perp_tol=0.1, random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [28]:
## Pipline Example
from sklearn.datasets import fetch_20newsgroups

#Initialize Variables
n_samples = 2000
n_features = 1000
n_topics = 10

dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))

INFO:sklearn.datasets.twenty_newsgroups:Downloading 20news dataset. This may take a few minutes.
INFO:sklearn.datasets.twenty_newsgroups:Downloading dataset from https://ndownloader.figshare.com/files/5975967 (14 MB)


In [30]:
len(dataset['data'])

11314

In [31]:
data_samples = dataset.data[:n_samples]

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

# Setup a tf vectorizer
tf_vectorizer = CountVectorizer(max_df=0.95,
                                min_df=2,
                                max_features=n_features,
                                stop_words='english')

tf = tf_vectorizer.fit_transform(data_samples)

In [37]:
lda = LatentDirichletAllocation(n_topics=20,
                               max_iter=5,
                               learning_method='online',
                               learning_offset=50.,
                               random_state=0)

In [38]:
tf

<2000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 51752 stored elements in Compressed Sparse Row format>

In [39]:
lda.fit(tf)  ## Success to this point

c:\users\anthony\scripts\nfl-topics\venv\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=5, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=20, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

# Step 6: NMF and LDA from scikit-learn docs

In [1]:
n_samples = 2000
n_features = 1000
n_topics = 10
n_top_words = 10

In [37]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import NMF, LatentDirichletAllocation
from time import time

In [3]:
# Load the 20 newsgroups dataset and vectorize it.  
# Use a few heuristics to filter out useless terms early on, the posts are stripped of headers,
# footers and quotes replies, and common english words, words occuring in only one document
# or in at least 95% of the documents re removed.

print("Loading dataset...")
t0 = time()
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
data_samples = dataset.data[:n_samples]
print("done in %0.fs." % (time() - t0))

Loading dataset...
done in 2s.


In [4]:
len(dataset.data)

11314

In [5]:
# TF-IDF Vectorization
print("Extracting tf-idf features for NMF...")
tfidf_vectorizer = TfidfVectorizer(max_df=.95,
                                   min_df=2,
                                   max_features=n_features,
                                   stop_words='english')

t0 = time()
tfidf = tfidf_vectorizer.fit_transform(data_samples)
print("done in %0.3fs." % (time() - t0))


Extracting tf-idf features for NMF...
done in 0.522s.


In [16]:
featuresIdf = tfidf_vectorizer.get_feature_names()

In [17]:
len(featuresIdf)

1000

In [18]:
featuresIdf

['00',
 '000',
 '10',
 '100',
 '11',
 '12',
 '128',
 '13',
 '130',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '1992',
 '1993',
 '20',
 '200',
 '21',
 '22',
 '23',
 '24',
 '25',
 '250',
 '26',
 '27',
 '28',
 '29',
 '2nd',
 '30',
 '300',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '3d',
 '40',
 '42',
 '43',
 '44',
 '45',
 '48',
 '49',
 '50',
 '500',
 '51',
 '55',
 '60',
 '66',
 '70',
 '72',
 '75',
 '80',
 '800',
 '86',
 '90',
 '92',
 '93',
 '__',
 'able',
 'ac',
 'accept',
 'access',
 'according',
 'act',
 'action',
 'actually',
 'add',
 'added',
 'addition',
 'address',
 'administration',
 'advance',
 'age',
 'ago',
 'agree',
 'aids',
 'air',
 'al',
 'allow',
 'allowed',
 'alt',
 'america',
 'american',
 'amiga',
 'analysis',
 'anonymous',
 'answer',
 'answers',
 'anti',
 'anybody',
 'apartment',
 'appears',
 'apple',
 'application',
 'applications',
 'apply',
 'appreciated',
 'approach',
 'appropriate',
 'apr',
 'april',
 'archive',
 'area',
 'areas',
 'aren',
 'argument',

In [15]:
# TF Vectorization - raw term counts
print("Extracting tf features for LDA...")
tf_vectorizer = CountVectorizer(max_df=.95,
                                min_df=2,
                                ngram_range=(1,3),
                                max_features=n_features,
                                stop_words='english')

t0 = time()
tf = tf_vectorizer.fit_transform(data_samples)
print('done in %0.3fs.' % (time() - t0))

Extracting tf features for LDA...
done in 2.588s.


In [19]:
features = tf_vectorizer.get_feature_names()

In [20]:
type(features)

list

In [27]:
tfidf.shape

(2000, 1000)

In [28]:
tf.shape

(2000, 1000)

In [60]:
# The print top words function
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        message = "Topic #%d: " % topic_idx
        message += " ".join([feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)
    print()
        

In [ ]:
# NMF Model

In [56]:
print("Fitting the NMF model with tf-idf freatures,  "
      'n_samples=%d and n_features=%d...'
      % (n_samples, n_features))

t0 = time()

nmf = NMF(n_components=n_topics,
          random_state=1,
          alpha=.1,
          l1_ratio=.5)

nmfResult = nmf.fit(tfidf)
print("done in %0.3fs." % (time() - t0))

tfidf_feature_names = tfidf_vectorizer.get_feature_names()

Fitting the NMF model with tf-idf freatures,  n_samples=2000 and n_features=1000...
done in 0.407s.


In [57]:
tfidf.shape

(2000, 1000)

In [58]:
nmf.components_.shape

(10, 1000)

In [61]:
print("Topics in NMF model:")
print_top_words(nmf, tfidf_feature_names, n_top_words)

Topics in NMF model:
Topic #0: just people don think like know time good make way
Topic #1: windows use dos using window program os drivers application help
Topic #2: god jesus bible faith christian christ christians does heaven sin
Topic #3: thanks know does mail advance hi info interested email anybody
Topic #4: car cars tires miles 00 new engine insurance price condition
Topic #5: edu soon com send university internet mit ftp mail cc
Topic #6: file problem files format win sound ftp pub read save
Topic #7: game team games year win play season players nhl runs
Topic #8: drive drives hard disk floppy software card mac computer power
Topic #9: key chip clipper keys encryption government public use secure enforcement



In [ ]:
# NMF Model with generalized Kullback-Leibler divergence

In [64]:
print("Fitting the NMF model (generalized Kullback-Leibler divergence) with tf-idf freatures,  "
      'n_samples=%d and n_features=%d...'
      % (n_samples, n_features))

t0 = time()

nmf = NMF(n_components=n_topics,
          random_state=1,
          beta_loss='kullback-leibler',
          solver='mu',
          max_iter=1000,
          alpha=.1,
          l1_ratio=.5)

nmfResult = nmf.fit(tfidf)
print("done in %0.3fs." % (time() - t0))

tfidf_feature_names = tfidf_vectorizer.get_feature_names()

Fitting the NMF model (generalized Kullback-Leibler divergence) with tf-idf freatures,  n_samples=2000 and n_features=1000...
done in 2.481s.


In [67]:
print("Topics in NMF model:")
print_top_words(nmf, tfidf_feature_names, n_top_words)

Topics in NMF model:
Topic #0: people just like time don say really know way things
Topic #1: windows thanks using help need hi work know use looking
Topic #2: god does true read know say believe subject says religion
Topic #3: thanks know like interested mail just want new send edu
Topic #4: time new 10 year sale old offer 20 16 15
Topic #5: use number com government new university data states information talk
Topic #6: edu try file soon remember problem com program hope mike
Topic #7: year world team game play won win games season maybe
Topic #8: think don drive need hard make people mac read going
Topic #9: just good use way got like ll doesn want sure



In [ ]:
# LDA Model

In [68]:
print("Fitting the LDA model  with tf freatures,  "
      'n_samples=%d and n_features=%d...'
      % (n_samples, n_features))

t0 = time()

lda = LatentDirichletAllocation(n_components=n_topics,
                                max_iter=5,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0,
                                )

lda.fit(tf)
print("done in %0.3fs." % (time() - t0))

tf_feature_names = tf_vectorizer.get_feature_names()

Fitting the LDA model  with tf freatures,  n_samples=2000 and n_features=1000...
done in 7.212s.


In [69]:
print("Topics in LDA model:")
print_top_words(lda, tf_feature_names, n_top_words)

Topics in LDA model:
Topic #0: space 10 earth 12 moon surface probe 93 00 lunar
Topic #1: game scsi play team flyers season games cubs color points
Topic #2: people just don think like know god time say make
Topic #3: thanks know like does bike don help interested advance looking
Topic #4: section military division win weapon firearm dangerous license shall application
Topic #5: edu windows com file mail graphics version software send ftp
Topic #6: just car like new good don year think better cars
Topic #7: 55 11 10 18 15 17 25 26 22 23
Topic #8: health hiv new national president aids information disease pittsburgh united
Topic #9: drive disk card hard drives speed power controller hard disk rom

